server:
  ssl:
    enabled: true
    key-store: classpath:server.jks
    key-store-password: changeit
    key-store-type: JKS
    key-alias: thinktech

remote:
  services:
    url: https://spring-consul
    ssl:
      key-store: classpath:server.jks
      key-store-password: changeit
      key-store-type: JKS


spring:
  cloud:
    consul:
      discovery:
        health-check-tls-skip-verify: true
        scheme: https
